# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alexl\OneDrive - ETH Zurich\Sonstiges\2021.08.26 - Python Wetterdaten\WeatherProgram.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 397)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressourcen/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelFolder = QtWidgets.QLabel(self.centralwidget)
        self.labelFolder.setGeometry(QtCore.QRect(190, 10, 270, 25))
        self.labelFolder.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.labelFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFolder.setObjectName("labelFolder")
        self.buttonLoadFolder = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoadFolder.setGeometry(QtCore.QRect(10, 10, 110, 25))
        self.buttonLoadFolder.setObjectName("buttonLoadFolder")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(135, 10, 45, 25))
        self.label.setObjectName("label")
        self.dateTimeStart = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeStart.setGeometry(QtCore.QRect(10, 130, 140, 22))
        self.dateTimeStart.setCalendarPopup(True)
        self.dateTimeStart.setObjectName("dateTimeStart")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 150, 45))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 47, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 110, 47, 16))
        self.label_4.setObjectName("label_4")
        self.dateTimeEnd = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEnd.setGeometry(QtCore.QRect(170, 130, 140, 22))
        self.dateTimeEnd.setCalendarPopup(True)
        self.dateTimeEnd.setObjectName("dateTimeEnd")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 110, 131, 16))
        self.label_5.setObjectName("label_5")
        self.lineEditTimeFormat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTimeFormat.setGeometry(QtCore.QRect(330, 130, 140, 22))
        self.lineEditTimeFormat.setObjectName("lineEditTimeFormat")
        self.buttonCreatePlot = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCreatePlot.setGeometry(QtCore.QRect(10, 320, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.buttonCreatePlot.setFont(font)
        self.buttonCreatePlot.setMouseTracking(False)
        self.buttonCreatePlot.setObjectName("buttonCreatePlot")
        self.checkBoxSecAxis = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxSecAxis.setGeometry(QtCore.QRect(490, 130, 121, 22))
        self.checkBoxSecAxis.setObjectName("checkBoxSecAxis")
        self.listWidgetYAxis = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetYAxis.setGeometry(QtCore.QRect(10, 190, 261, 111))
        self.listWidgetYAxis.setAlternatingRowColors(True)
        self.listWidgetYAxis.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidgetYAxis.setObjectName("listWidgetYAxis")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 211, 16))
        self.label_6.setObjectName("label_6")
        self.labelPlotSecAxis = QtWidgets.QLabel(self.centralwidget)
        self.labelPlotSecAxis.setEnabled(True)
        self.labelPlotSecAxis.setGeometry(QtCore.QRect(290, 170, 181, 16))
        self.labelPlotSecAxis.setObjectName("labelPlotSecAxis")
        self.listWidgetSecYAxis = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetSecYAxis.setEnabled(True)
        self.listWidgetSecYAxis.setGeometry(QtCore.QRect(290, 190, 261, 111))
        self.listWidgetSecYAxis.setAlternatingRowColors(True)
        self.listWidgetSecYAxis.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidgetSecYAxis.setObjectName("listWidgetSecYAxis")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuHilfe = QtWidgets.QMenu(self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionLink_zu_GitHub = QtWidgets.QAction(MainWindow)
        self.actionLink_zu_GitHub.setObjectName("actionLink_zu_GitHub")
        self.action_ber = QtWidgets.QAction(MainWindow)
        self.action_ber.setObjectName("action_ber")
        self.menuDatei.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionLink_zu_GitHub)
        self.menuHilfe.addAction(self.action_ber)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wetterdaten Visualisierung"))
        self.labelFolder.setToolTip(_translate("MainWindow", "Ordner mit allen einzulesenden Dateien der Wetterdaten"))
        self.labelFolder.setText(_translate("MainWindow", "--- noch kein Ordner ausgewählt ---"))
        self.buttonLoadFolder.setText(_translate("MainWindow", "Lade Wetterdateien"))
        self.label.setText(_translate("MainWindow", "Ordner: "))
        self.label_2.setText(_translate("MainWindow", "Setup"))
        self.label_3.setText(_translate("MainWindow", "Startzeit"))
        self.label_4.setText(_translate("MainWindow", "Endzeit"))
        self.label_5.setText(_translate("MainWindow", "Zeitachsen-Beschriftung"))
        self.lineEditTimeFormat.setToolTip(_translate("MainWindow", "<html><head/><body><p>Gibt das Format der Zeitachsen-Beschriftung im Plot an.</p><p>Wenn Sie sich nicht sicher sind, was das bedeutet: NICHT ändern!</p></body></html>"))
        self.lineEditTimeFormat.setText(_translate("MainWindow", "%d.%m.%Y"))
        self.buttonCreatePlot.setToolTip(_translate("MainWindow", "Erstellt den Plot mit obigen Einstellungen."))
        self.buttonCreatePlot.setText(_translate("MainWindow", "Erstelle Plot"))
        self.checkBoxSecAxis.setText(_translate("MainWindow", "Zwei Achsen"))
        self.label_6.setText(_translate("MainWindow", "Plotte auf y-Achse"))
        self.labelPlotSecAxis.setText(_translate("MainWindow", "Plotte auf zweiter y-Achse"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionLink_zu_GitHub.setText(_translate("MainWindow", "Link zu GitHub"))
        self.action_ber.setText(_translate("MainWindow", "Über"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

